highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Pulkit Katdare's Resume
name: Pulkit Katdare
email: pulkitkatdare@iitb.ac.in
email_full: mailto:pulkitkatdare@gmail.com
website: pulkitkatdare.github.io
website_full: https://pulkitkatdare.github.io
github: pulkitkatdare
twitter: pulkitkatdare
tel: +91 7506 168628
tel_full: tel:+91 7506 168628
google_maps: 'https://www.google.co.in/maps/place/Hostel+6/@19.1356886,72.9050142,17z/data=!3m1!4b1!4m5!3m4!1s0x3be7b8070da216d3:0x2825de5bf4b0c839!8m2!3d19.1356886!4d72.9072029'
address: 191, Hostel 6, IIT Bombay
postcode: 400076
city: Mumbai
country: India
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
